#@ load("@ytt:data", "data")

#@ if data.values.policies.include:
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: source-controller-verify-image
  namespace: flux-system
  annotations:
    policies.kyverno.io/title: Verify Image
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.9.0
    policies.kyverno.io/description: >-
      Using the Cosign project, this policy checks all container images used by this package
      to ensure they have been signed by verifying their signatures against the provided public key. 
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-signature
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/fluxcd/*"
        - "docker.io/fluxcd/*"
        attestors:
        - entries:
          - keyless:
              #! https://fluxcd.io/flux/security/#signed-container-images
              subject: "https://github.com/fluxcd/*"
              issuer: "https://token.actions.githubusercontent.com"
              rekor:
                url: https://rekor.sigstore.dev
#@ end
